displayName=Slayer Swaps
author=Jetsmoke
description=Automatically swaps menu entries, and highlights teleport items and spells to quickly teleport to your slayer task. Supports choosing your preferred slayer master and preferred task location. To start right click your slayer helmet or check settings panel.
tags=slayer,teleport,menu,swap,highlight,fairy ring,slayer ring,task,master
version=1.0.1
plugins=com.slayerswaps.SlayerSwapsPlugin
build=standard
