package com.slayerswaps;

/**
 * Konar's tasks and areas the testing plugin can pretend to have.
 * Generated by tools/gen_simulated_tasks.py from slayer_locations.json; don't edit by hand.
 */
public enum KonarTestTask
{
	OFF(null, null),
	ABERRANT_SPECTRES_CATACOMBS_OF_KOUREND("Aberrant spectres", "Catacombs of Kourend"),
	ABERRANT_SPECTRES_SLAYER_TOWER("Aberrant spectres", "Slayer Tower"),
	ABERRANT_SPECTRES_STRONGHOLD_SLAYER_CAVE("Aberrant spectres", "Stronghold Slayer Cave"),
	ABYSSAL_DEMONS_CATACOMBS_OF_KOUREND("Abyssal demons", "Catacombs of Kourend"),
	ABYSSAL_DEMONS_ABYSS("Abyssal demons", "Abyss"),
	ABYSSAL_DEMONS_SLAYER_TOWER("Abyssal demons", "Slayer Tower"),
	ANKOU_STRONGHOLD_OF_SECURITY("Ankou", "Stronghold of Security"),
	ANKOU_STRONGHOLD_SLAYER_DUNGEON("Ankou", "Stronghold Slayer Dungeon"),
	ANKOU_CATACOMBS_OF_KOUREND("Ankou", "Catacombs of Kourend"),
	AVIANSIE_GOD_WARS_DUNGEON("Aviansie", "God Wars Dungeon"),
	BASILISKS_FREMENNIK_SLAYER_DUNGEON("Basilisks", "Fremennik Slayer Dungeon"),
	BASILISKS_JORMUNGAND_S_PRISON("Basilisks", "Jormungand's Prison"),
	BLACK_DEMONS_CATACOMBS_OF_KOUREND("Black demons", "Catacombs of Kourend"),
	BLACK_DEMONS_CHASM_OF_FIRE("Black demons", "Chasm of Fire"),
	BLACK_DEMONS_TAVERLEY_DUNGEON("Black demons", "Taverley Dungeon"),
	BLACK_DEMONS_BRIMHAVEN_DUNGEON("Black demons", "Brimhaven Dungeon"),
	BLACK_DRAGONS_CATACOMBS_OF_KOUREND("Black dragons", "Catacombs of Kourend"),
	BLACK_DRAGONS_MYTHS_GUILD_DUNGEON("Black dragons", "Myths' Guild Dungeon"),
	BLACK_DRAGONS_EVIL_CHICKEN_S_LAIR("Black dragons", "Evil Chicken's Lair"),
	BLACK_DRAGONS_TAVERLEY_DUNGEON("Black dragons", "Taverley Dungeon"),
	BLOODVELDS_CATACOMBS_OF_KOUREND("Bloodvelds", "Catacombs of Kourend"),
	BLOODVELDS_GOD_WARS_DUNGEON("Bloodvelds", "God Wars Dungeon"),
	BLOODVELDS_IORWERTH_DUNGEON("Bloodvelds", "Iorwerth Dungeon"),
	BLOODVELDS_MEIYERDITCH_LABORATORIES("Bloodvelds", "Meiyerditch Laboratories"),
	BLOODVELDS_SLAYER_TOWER("Bloodvelds", "Slayer Tower"),
	BLOODVELDS_STRONGHOLD_SLAYER_DUNGEON("Bloodvelds", "Stronghold Slayer Dungeon"),
	BLUE_DRAGONS_CATACOMBS_OF_KOUREND("Blue dragons", "Catacombs of Kourend"),
	BLUE_DRAGONS_ISLE_OF_SOULS_DUNGEON("Blue dragons", "Isle of Souls Dungeon"),
	BLUE_DRAGONS_MYTHS_GUILD_DUNGEON("Blue dragons", "Myths' Guild Dungeon"),
	BLUE_DRAGONS_OGRE_ENCLAVE("Blue dragons", "Ogre Enclave"),
	BLUE_DRAGONS_RUINS_OF_TAPOYAUIK("Blue dragons", "Ruins of Tapoyauik"),
	BLUE_DRAGONS_TAVERLEY_DUNGEON("Blue dragons", "Taverley Dungeon"),
	BRINE_RAT_BRINE_RAT_CAVERN("Brine rat", "Brine Rat Cavern"),
	CAVE_KRAKEN_KRAKEN_COVE("Cave kraken", "Kraken Cove"),
	DAGANNOTH_CATACOMBS_OF_KOUREND("Dagannoth", "Catacombs of Kourend"),
	DAGANNOTH_LIGHTHOUSE("Dagannoth", "Lighthouse"),
	DAGANNOTH_WATERBIRTH_ISLAND("Dagannoth", "Waterbirth Island"),
	DAGANNOTH_JORMUNGAND_S_PRISON("Dagannoth", "Jormungand's Prison"),
	DARK_BEASTS_MOURNER_TUNNELS("Dark beasts", "Mourner Tunnels"),
	DARK_BEASTS_IORWERTH_DUNGEON("Dark beasts", "Iorwerth Dungeon"),
	DRAKES_KARUULM_SLAYER_DUNGEON("Drakes", "Karuulm Slayer Dungeon"),
	DUST_DEVILS_CATACOMBS_OF_KOUREND("Dust devils", "Catacombs of Kourend"),
	DUST_DEVILS_SMOKE_DUNGEON("Dust devils", "Smoke Dungeon"),
	FIRE_GIANTS_BRIMHAVEN_DUNGEON("Fire giants", "Brimhaven Dungeon"),
	FIRE_GIANTS_CATACOMBS_OF_KOUREND("Fire giants", "Catacombs of Kourend"),
	FIRE_GIANTS_ISLE_OF_SOULS_DUNGEON("Fire giants", "Isle of Souls Dungeon"),
	FIRE_GIANTS_GIANTS_DEN("Fire giants", "Giants' Den"),
	FIRE_GIANTS_KARUULM_SLAYER_DUNGEON("Fire giants", "Karuulm Slayer Dungeon"),
	FIRE_GIANTS_STRONGHOLD_SLAYER_DUNGEON("Fire giants", "Stronghold Slayer Dungeon"),
	FIRE_GIANTS_WATERFALL_DUNGEON("Fire giants", "Waterfall Dungeon"),
	FOSSIL_ISLAND_WYVERNS_WYVERN_CAVE("Fossil Island Wyverns", "Wyvern Cave"),
	GARGOYLES_SLAYER_TOWER("Gargoyles", "Slayer Tower"),
	GREATER_DEMONS_CATACOMBS_OF_KOUREND("Greater demons", "Catacombs of Kourend"),
	GREATER_DEMONS_CHASM_OF_FIRE("Greater demons", "Chasm of Fire"),
	GREATER_DEMONS_ISLE_OF_SOULS_DUNGEON("Greater demons", "Isle of Souls Dungeon"),
	GREATER_DEMONS_KARUULM_SLAYER_DUNGEON("Greater demons", "Karuulm Slayer Dungeon"),
	GREATER_DEMONS_BRIMHAVEN_DUNGEON("Greater demons", "Brimhaven Dungeon"),
	HELLHOUNDS_KARUULM_SLAYER_DUNGEON("Hellhounds", "Karuulm Slayer Dungeon"),
	HELLHOUNDS_CATACOMBS_OF_KOUREND("Hellhounds", "Catacombs of Kourend"),
	HELLHOUNDS_STRONGHOLD_SLAYER_DUNGEON("Hellhounds", "Stronghold Slayer Dungeon"),
	HELLHOUNDS_TAVERLEY_DUNGEON("Hellhounds", "Taverley Dungeon"),
	HELLHOUNDS_WITCHAVEN_DUNGEON("Hellhounds", "Witchaven Dungeon"),
	HYDRAS_KARUULM_SLAYER_DUNGEON("Hydras", "Karuulm Slayer Dungeon"),
	JELLIES_FREMENNIK_SLAYER_DUNGEON("Jellies", "Fremennik Slayer Dungeon"),
	JELLIES_CATACOMBS_OF_KOUREND("Jellies", "Catacombs of Kourend"),
	JELLIES_RUINS_OF_TAPOYAUIK("Jellies", "Ruins of Tapoyauik"),
	KALPHITES_KALPHITE_LAIR("Kalphites", "Kalphite Lair"),
	KALPHITES_KALPHITE_CAVE("Kalphites", "Kalphite Cave"),
	KURASKS_FREMENNIK_SLAYER_DUNGEON("Kurasks", "Fremennik Slayer Dungeon"),
	KURASKS_IORWERTH_DUNGEON("Kurasks", "Iorwerth Dungeon"),
	LESSER_NAGUA_NEYPOTZLI("Lesser Nagua", "Neypotzli"),
	LESSER_NAGUA_RUINS_OF_TAPOYAUIK("Lesser Nagua", "Ruins of Tapoyauik"),
	LESSER_NAGUA_CRYPT_OF_TONALI("Lesser Nagua", "Crypt of Tonali"),
	LIZARDMEN_BATTLEFRONT("Lizardmen", "Battlefront"),
	LIZARDMEN_LIZARDMAN_CANYON("Lizardmen", "Lizardman Canyon"),
	LIZARDMEN_LIZARDMAN_SETTLEMENT("Lizardmen", "Lizardman Settlement"),
	LIZARDMEN_KEBOS_SWAMP("Lizardmen", "Kebos Swamp"),
	LIZARDMEN_MOLCH("Lizardmen", "Molch"),
	METAL_DRAGONS_BRIMHAVEN_DUNGEON("Metal dragons", "Brimhaven Dungeon"),
	METAL_DRAGONS_CATACOMBS_OF_KOUREND("Metal dragons", "Catacombs of Kourend"),
	METAL_DRAGONS_ISLE_OF_SOULS_DUNGEON("Metal dragons", "Isle of Souls Dungeon"),
	METAL_DRAGONS_LITHKREN_VAULT("Metal dragons", "Lithkren Vault"),
	NECHRYAEL_CATACOMBS_OF_KOUREND("Nechryael", "Catacombs of Kourend"),
	NECHRYAEL_IORWERTH_DUNGEON("Nechryael", "Iorwerth Dungeon"),
	NECHRYAEL_SLAYER_TOWER("Nechryael", "Slayer Tower"),
	RED_DRAGONS_BRIMHAVEN_DUNGEON("Red dragons", "Brimhaven Dungeon"),
	RED_DRAGONS_CATACOMBS_OF_KOUREND("Red dragons", "Catacombs of Kourend"),
	RED_DRAGONS_FORTHOS_DUNGEON("Red dragons", "Forthos Dungeon"),
	RED_DRAGONS_MYTHS_GUILD_DUNGEON("Red dragons", "Myths' Guild Dungeon"),
	SKELETAL_WYVERN_ASGARNIAN_ICE_DUNGEON("Skeletal Wyvern", "Asgarnian Ice Dungeon"),
	SMOKE_DEVILS_SMOKE_DEVIL_DUNGEON("Smoke devils", "Smoke Devil Dungeon"),
	TROLLS_TROLL_STRONGHOLD("Trolls", "Troll Stronghold"),
	TROLLS_KELDAGRIM("Trolls", "Keldagrim"),
	TROLLS_DEATH_PLATEAU("Trolls", "Death Plateau"),
	TROLLS_FREMENNIK_ISLES("Trolls", "Fremennik Isles"),
	TROLLS_WYRMSCRAIG_CAVERN("Trolls", "Wyrmscraig Cavern"),
	TUROTH_FREMENNIK_SLAYER_DUNGEON("Turoth", "Fremennik Slayer Dungeon"),
	VAMPYRES_DARKMEYER("Vampyres", "Darkmeyer"),
	VAMPYRES_MEIYERDITCH("Vampyres", "Meiyerditch"),
	VAMPYRES_SLEPE("Vampyres", "Slepe"),
	VAMPYRES_VAMPYRIUM("Vampyres", "Vampyrium"),
	WARPED_CREATURES_POISON_WASTE_DUNGEON("Warped creatures", "Poison Waste Dungeon"),
	WATERFIENDS_ANCIENT_CAVERN("Waterfiends", "Ancient Cavern"),
	WATERFIENDS_IORWERTH_DUNGEON("Waterfiends", "Iorwerth Dungeon"),
	WATERFIENDS_KRAKEN_COVE("Waterfiends", "Kraken Cove"),
	WYRMS_KARUULM_SLAYER_DUNGEON("Wyrms", "Karuulm Slayer Dungeon"),
	WYRMS_NEYPOTZLI("Wyrms", "Neypotzli"),
	WYRMS_CHARRED_DUNGEON("Wyrms", "Charred Dungeon"),
	WYRMS_WYRMSCRAIG("Wyrms", "Wyrmscraig"),
	ZYGOMITES_FOSSIL_ISLAND("Zygomites", "Fossil Island"),
	ZYGOMITES_ZANARIS("Zygomites", "Zanaris");

	// Task name as in slayer_locations.json, and Konar's area, or null
	private final String task;
	private final String area;

	KonarTestTask(String task, String area)
	{
		this.task = task;
		this.area = area;
	}

	public String getTask()
	{
		return task;
	}

	public String getArea()
	{
		return area;
	}

	@Override
	public String toString()
	{
		return task == null ? "Off" : task + ": " + area;
	}
}
