package com.slayerswaps;

/**
 * Tasks the testing plugin can pretend to have.
 * Generated by tools/gen_simulated_tasks.py from slayer_locations.json; don't edit by hand.
 */
public enum SimulatedTask
{
	OFF(null),
	NO_TASK(null),
	ABERRANT_SPECTRES("Aberrant spectres"),
	ABYSSAL_DEMONS("Abyssal demons"),
	ABYSSAL_SIRE("Abyssal Sire"),
	ALCHEMICAL_HYDRA("Alchemical Hydra"),
	ANKOU("Ankou"),
	AQUANITES("Aquanites"),
	ARAXXOR("Araxxor"),
	ARAXYTES("Araxytes"),
	AVIANSIE("Aviansie"),
	BANDITS("Bandits"),
	BANSHEES("Banshees"),
	BARROWS("Barrows"),
	BASILISKS("Basilisks"),
	BATS("Bats"),
	BEARS("Bears"),
	BIRDS("Birds"),
	BLACK_DEMONS("Black demons"),
	BLACK_DRAGONS("Black dragons"),
	BLACK_KNIGHT("Black Knight"),
	BLOODVELDS("Bloodvelds"),
	BLUE_DRAGONS("Blue dragons"),
	BRINE_RAT("Brine rat"),
	CALLISTO("Callisto"),
	CATABLEPON("Catablepon"),
	CAVE_BUG("Cave bug"),
	CAVE_CRAWLERS("Cave crawlers"),
	CAVE_HORRORS("Cave horrors"),
	CAVE_KRAKEN("Cave kraken"),
	CAVE_SLIME("Cave slime"),
	CERBERUS("Cerberus"),
	CHAOS_DRUID("Chaos druid"),
	CHAOS_ELEMENTAL("Chaos Elemental"),
	CHAOS_FANATIC("Chaos Fanatic"),
	COCKATRICE("Cockatrice"),
	COMMANDER_ZILYANA("Commander Zilyana"),
	COWS("Cows"),
	CRABS("Crabs"),
	CRAWLING_HAND("Crawling Hand"),
	CRAZY_ARCHAEOLOGIST("Crazy archaeologist"),
	CROCODILE("Crocodile"),
	CUSTODIAN_STALKERS("Custodian stalkers"),
	DAGANNOTH("Dagannoth"),
	DAGANNOTH_KINGS("Dagannoth Kings"),
	DARK_BEASTS("Dark beasts"),
	DARK_WARRIOR("Dark warrior"),
	DOGS("Dogs"),
	DRAKES("Drakes"),
	DUKE_SUCELLUS("Duke Sucellus"),
	DUST_DEVILS("Dust devils"),
	DWARVES("Dwarves"),
	EARTH_WARRIORS("Earth Warriors"),
	ELVES("Elves"),
	ENT("Ent"),
	FEVER_SPIDER("Fever spider"),
	FIRE_GIANTS("Fire giants"),
	FLESH_CRAWLER("Flesh Crawler"),
	FOSSIL_ISLAND_WYVERNS("Fossil Island Wyverns"),
	FROST_DRAGON("Frost dragon"),
	GARGOYLES("Gargoyles"),
	GENERAL_GRAARDOR("General Graardor"),
	GHOSTS("Ghosts"),
	GHOUL("Ghoul"),
	GIANT_MOLE("Giant Mole"),
	GOBLINS("Goblins"),
	GREATER_DEMONS("Greater demons"),
	GREEN_DRAGONS("Green dragons"),
	GROTESQUE_GUARDIANS("Grotesque Guardians"),
	GRYPHONS("Gryphons"),
	HARPIE_BUG_SWARM("Harpie bug swarm"),
	HELLHOUNDS("Hellhounds"),
	HILL_GIANTS("Hill Giants"),
	HOBGOBLINS("Hobgoblins"),
	HYDRAS("Hydras"),
	ICE_GIANTS("Ice giants"),
	ICE_WARRIOR("Ice warrior"),
	ICEFIEND("Icefiend"),
	INFERNAL_MAGE("Infernal Mage"),
	JELLIES("Jellies"),
	JUNGLE_HORROR("Jungle horror"),
	K_RIL_TSUTSAROTH("K'ril Tsutsaroth"),
	KALPHITE_QUEEN("Kalphite Queen"),
	KALPHITES("Kalphites"),
	KILLERWATT("Killerwatt"),
	KING_BLACK_DRAGON("King Black Dragon"),
	KRAKEN("Kraken"),
	KREE_ARRA("Kree'arra"),
	KURASKS("Kurasks"),
	LAVA_DRAGON("Lava dragon"),
	LESSER_DEMONS("Lesser demons"),
	LESSER_NAGUA("Lesser Nagua"),
	LIZARDMEN("Lizardmen"),
	LIZARDS("Lizards"),
	MAGGOT_KING("Maggot King"),
	MAGIC_AXE("Magic axe"),
	MAMMOTH("Mammoth"),
	METAL_DRAGONS("Metal dragons"),
	MINOTAUR("Minotaur"),
	MOGRES("Mogres"),
	MOLANISKS("Molanisks"),
	MONKEYS("Monkeys"),
	MOSS_GIANTS("Moss giants"),
	NECHRYAEL("Nechryael"),
	OGRES("Ogres"),
	OTHERWORLDLY_BEING("Otherworldly being"),
	PHANTOM_MUSPAH("Phantom Muspah"),
	PIRATES("Pirates"),
	PYREFIENDS("Pyrefiends"),
	RATS("Rats"),
	RED_DRAGONS("Red dragons"),
	REVENANT("Revenant"),
	ROCKSLUG("Rockslug"),
	ROGUE("Rogue"),
	SARACHNIS("Sarachnis"),
	SCABARITES("Scabarites"),
	SCORPIA("Scorpia"),
	SCORPIONS("Scorpions"),
	SEA_SNAKES("Sea snakes"),
	SHADES("Shades"),
	SHADOW_WARRIOR("Shadow warrior"),
	SHELLBANE_GRYPHON("Shellbane gryphon"),
	SKELETAL_WYVERN("Skeletal Wyvern"),
	SKELETONS("Skeletons"),
	SMOKE_DEVILS("Smoke devils"),
	SOURHOG("Sourhog"),
	SPIDERS("Spiders"),
	SPIRITUAL_CREATURES("Spiritual creatures"),
	SUQAHS("Suqahs"),
	TERROR_DOG("Terror dog"),
	THE_LEVIATHAN("The Leviathan"),
	THE_WHISPERER("The Whisperer"),
	THERMONUCLEAR_SMOKE_DEVIL("Thermonuclear smoke devil"),
	TROLLS("Trolls"),
	TUROTH("Turoth"),
	TZHAAR("TzHaar"),
	TZKAL_ZUK("TzKal-Zuk"),
	TZTOK_JAD("TzTok-Jad"),
	VAMPYRES("Vampyres"),
	VARDORVIS("Vardorvis"),
	VENATORS("Venators"),
	VENENATIS("Venenatis"),
	VET_ION("Vet'ion"),
	VORKATH("Vorkath"),
	WALL_BEASTS("Wall Beasts"),
	WARPED_CREATURES("Warped creatures"),
	WATERFIENDS("Waterfiends"),
	WEREWOLVES("Werewolves"),
	WOLVES("Wolves"),
	WYRMS("Wyrms"),
	ZOMBIES("Zombies"),
	ZULRAH("Zulrah"),
	ZYGOMITES("Zygomites");

	// Task name as in slayer_locations.json, or null
	private final String task;

	SimulatedTask(String task)
	{
		this.task = task;
	}

	public String getTask()
	{
		return task;
	}

	@Override
	public String toString()
	{
		switch (this)
		{
			case OFF:
				return "Off";
			case NO_TASK:
				return "No task";
			default:
				return task;
		}
	}
}
