"""
Teleport catalog: items, spells and Wilderness obelisks the plugin can highlight, with their in-game destination
options (from each item's wiki infobox "options"/"wornoptions"). `syn` maps words seen in
wiki directions to the option they mean.
"""
ITEMS = {
    # key: label, name prefixes (lower-case item names), destination options, synonyms -> option
    'ghommals_hilt': ("Ghommal's hilt", ["ghommal's hilt"], ['Trollheim', 'Mor Ul Rek'],
                      {'god wars': 'Trollheim', 'trollheim': 'Trollheim', 'mor ul rek': 'Mor Ul Rek', 'tzhaar': 'Mor Ul Rek'}),
    'games_necklace': ('Games necklace', ['games necklace'],
                       ['Burthorpe', 'Barbarian Outpost', 'Corporeal Beast', 'Tears of Guthix', 'Wintertodt Camp'],
                       {'burthorpe': 'Burthorpe', 'barbarian outpost': 'Barbarian Outpost', 'corporeal': 'Corporeal Beast',
                        'tears of guthix': 'Tears of Guthix', 'wintertodt': 'Wintertodt Camp'}),
    'skills_necklace': ('Skills necklace', ['skills necklace'],
                        ['Fishing Guild', 'Mining Guild', 'Crafting Guild', 'Cooking Guild', 'Woodcutting Guild', 'Farming Guild'],
                        {'fishing guild': 'Fishing Guild', 'mining guild': 'Mining Guild', 'crafting guild': 'Crafting Guild',
                         "cooks' guild": 'Cooking Guild', 'cooking guild': 'Cooking Guild', 'woodcutting guild': 'Woodcutting Guild',
                         'farming guild': 'Farming Guild'}),
    'combat_bracelet': ('Combat bracelet', ['combat bracelet'],
                        ["Warriors' Guild", "Champions' Guild", 'Monastery', 'Ranging Guild'],
                        {"warriors' guild": "Warriors' Guild", "champions' guild": "Champions' Guild",
                         'edgeville monastery': 'Monastery', 'ranging guild': 'Ranging Guild'}),
    'ring_of_wealth': ('Ring of wealth', ['ring of wealth'], ['Miscellania', 'Grand Exchange', 'Falador', 'Dondakan'],
                       {'miscellania': 'Miscellania', 'grand exchange': 'Grand Exchange', 'falador park': 'Falador', 'dondakan': 'Dondakan'}),
    'xerics_talisman': ("Xeric's talisman", ["xeric's talisman"],
                        ["Xeric's Lookout", "Xeric's Glade", "Xeric's Inferno", "Xeric's Heart", "Xeric's Honour"],
                        {"xeric's lookout": "Xeric's Lookout", "xeric's glade": "Xeric's Glade", "xeric's inferno": "Xeric's Inferno",
                         "xeric's heart": "Xeric's Heart", "xeric's honour": "Xeric's Honour", 'shayzien': "Xeric's Lookout",
                         'hosidius': "Xeric's Glade", 'lovakengj': "Xeric's Inferno", 'kourend castle': "Xeric's Heart",
                         'quidamortem': "Xeric's Honour"}),
    'kharedsts_memoirs': ("Kharedst's memoirs / Book of the dead", ["kharedst's memoirs", 'book of the dead'],
                          ['Lunch by the Lancalliums', "The Fisher's Flute", 'History and Hearsay', 'Jewellery of Jubilation',
                           'A Dark Disposition'],
                          {'lancalliums': 'Lunch by the Lancalliums', 'hosidius': 'Lunch by the Lancalliums',
                           "fisher's flute": "The Fisher's Flute", 'piscarilius': "The Fisher's Flute",
                           'history and hearsay': 'History and Hearsay', 'shayzien': 'History and Hearsay',
                           'jewellery of jubilation': 'Jewellery of Jubilation', 'lovakengj': 'Jewellery of Jubilation',
                           'dark disposition': 'A Dark Disposition', 'arceuus': 'A Dark Disposition'}),
    'drakans_medallion': ("Drakan's medallion", ["drakan's medallion"], ['Ver Sinhaza', 'Darkmeyer', 'Slepe', 'Castle Drakan'],
                          {'ver sinhaza': 'Ver Sinhaza', 'darkmeyer': 'Darkmeyer', 'slepe': 'Slepe', 'castle drakan': 'Castle Drakan'}),
    'morytania_legs': ('Morytania legs 3/4', ['morytania legs 3', 'morytania legs 4'], ['Ecto Teleport', 'Burgh Teleport'],
                       {'ecto': 'Ecto Teleport', 'port phasmatys': 'Ecto Teleport', 'burgh de rott': 'Burgh Teleport', 'burgh': 'Burgh Teleport'}),
    'ardougne_cloak': ('Ardougne cloak', ['ardougne cloak', 'ardougne max cape'], ['Monastery Teleport', 'Farm Teleport'],
                       {'monastery': 'Monastery Teleport', 'farm': 'Farm Teleport'}),
    'ectophial': ('Ectophial', ['ectophial'], ['Teleport'], {}),
    'necklace_of_passage': ('Necklace of passage', ['necklace of passage'],
                            ["Wizards' Tower", 'The Outpost', "Eagles' Eyrie", 'Wyrmscraig'],
                            {"wizards' tower": "Wizards' Tower", 'outpost': 'The Outpost', "eagles' eyrie": "Eagles' Eyrie",
                             'wyrmscraig': 'Wyrmscraig'}),
    'digsite_pendant': ('Digsite pendant', ['digsite pendant'], ['Digsite', 'Fossil Island', 'Lithkren Dungeon'],
                        {'fossil island': 'Fossil Island', 'lithkren': 'Lithkren Dungeon', 'digsite': 'Digsite'}),
    'pendant_of_ates': ('Pendant of ates', ['pendant of ates'],
                        ['The Darkfrost', 'Twilight Temple', "Ralos' Rise", 'North Aldarin', 'North of Kastori', 'Nemus Retreat'],
                        {'darkfrost': 'The Darkfrost', 'twilight temple': 'Twilight Temple', "ralos' rise": "Ralos' Rise",
                         'aldarin': 'North Aldarin', 'kastori': 'North of Kastori', 'nemus': 'Nemus Retreat'}),
    'radas_blessing': ("Rada's blessing 3/4", ["rada's blessing 3", "rada's blessing 4"], ['Kourend Woodland', 'Mount Karuulm'],
                       {'karuulm': 'Mount Karuulm', 'kourend woodland': 'Kourend Woodland'}),
    'fremennik_sea_boots': ('Fremennik sea boots 4', ['fremennik sea boots 4'], ['Teleport'], {}),
    'desert_amulet': ('Desert amulet 4', ['desert amulet 4'], ['Nardah', 'Kalphite cave'],
                      {'nardah': 'Nardah', 'kalphite cave': 'Kalphite cave'}),
    'royal_seed_pod': ('Royal seed pod', ['royal seed pod'], ['Commune'], {}),
    'enchanted_lyre': ('Enchanted lyre', ['enchanted lyre'], ['Rellekka', 'Waterbirth Island', 'Jatizso', 'Neitiznot'],
                       {'rellekka': 'Rellekka', 'waterbirth': 'Waterbirth Island', 'jatizso': 'Jatizso', 'neitiznot': 'Neitiznot'}),
    'diary_cape': ('Achievement diary cape', ['achievement diary cape'], [], {}),
    'ring_of_shadows': ('Ring of shadows', ['ring of shadows'],
                        ['Ancient Vault', 'Ghorrock Dungeon', 'The Scar', 'Lassar Undercity', 'The Stranglewood'],
                        {'ancient vault': 'Ancient Vault', 'ghorrock': 'Ghorrock Dungeon', 'the scar': 'The Scar',
                         'lassar': 'Lassar Undercity', 'stranglewood': 'The Stranglewood'}),
    'teleport_crystal': ('Teleport crystal', ['teleport crystal', 'eternal teleport crystal'], ['Lletya', 'Prifddinas'],
                         {'lletya': 'Lletya', 'prifddinas': 'Prifddinas'}),
    'karamja_gloves_3': ('Karamja gloves 3/4', ['karamja gloves 3', 'karamja gloves 4'], ['Gem Mine'], {'gem mine': 'Gem Mine'}),
    'kandarin_headgear': ('Kandarin headgear 4', ['kandarin headgear 4'], ['Teleport'], {}),
    'western_banner': ('Western banner 3/4', ['western banner 3', 'western banner 4'], ['Teleport'], {}),
    # Hard (3) and elite (4) swords teleport to the Fountain of Rune
    'wilderness_sword': ('Wilderness sword 3/4', ['wilderness sword 3', 'wilderness sword 4'], ['Teleport'], {}),
    # Teleports to the dark crab fishing spot by the Silk Chasm
    'wilderness_crabs_teleport': ('Wilderness crabs teleport', ['wilderness crabs teleport'], ['Break'], {}),
    'mythical_cape': ('Mythical cape', ['mythical cape'], ['Teleport'], {}),
    'calcified_moth': ('Calcified moth', ['calcified moth'], ['Crush'], {}),
    'camulet': ('Camulet', ['camulet'], ['Teleport'], {}),
    'icy_basalt': ('Icy basalt', ['icy basalt'], ['Weiss'], {}),
    'stony_basalt': ('Stony basalt', ['stony basalt'], ['Troll Stronghold'], {}),
    'spider_cave_teleport': ('Spider cave teleport', ['spider cave teleport'], ['Teleport'], {}),
    'revenant_cave_teleport': ('Revenant cave teleport', ['revenant cave teleport'], ['Teleport'], {}),
    'mos_leharmless_teleport': ("Mos le'harmless teleport", ["mos le'harmless teleport"], ['Teleport'], {}),
    'mortton_teleport': ("Mort'ton teleport", ["mort'ton teleport"], ['Teleport'], {}),
    'lumberyard_teleport': ('Lumberyard teleport', ['lumberyard teleport'], ['Teleport'], {}),
    'hallowed_crystal_shard': ('Hallowed crystal shard', ['hallowed crystal shard'], ['Activate'], {}),
    'quest_point_cape': ('Quest point cape', ['quest point cape'], ['Teleport'], {}),
    'chronicle': ('Chronicle', ['chronicle'], ['Teleport'], {}),
    'fishing_cape': ('Fishing cape', ['fishing cape'], ['Fishing Guild', "Otto's Grotto"],
                     {'fishing guild': 'Fishing Guild', "otto's grotto": "Otto's Grotto", 'otto': "Otto's Grotto"}),
    'farming_cape': ('Farming cape', ['farming cape'], ['Teleport'], {}),
    'hunter_cape': ('Hunter cape', ['hunter cape'], ['Teleport'], {}),
    'crafting_cape': ('Crafting cape', ['crafting cape'], ['Teleport'], {}),
    'strength_cape': ('Strength cape', ['strength cape'], ["Warriors' Guild"], {}),
    'skull_sceptre': ('Skull sceptre', ['skull sceptre'], ['Invoke'], {}),
}

# Which wiki words name each item when it appears in directions
ITEM_ALIASES = {
    'ghommals_hilt': ["ghommal's hilt", 'combat achievement'],
    'games_necklace': ['games necklace'], 'skills_necklace': ['skills necklace'], 'combat_bracelet': ['combat bracelet'],
    'ring_of_wealth': ['ring of wealth'], 'xerics_talisman': ["xeric's talisman"],
    'kharedsts_memoirs': ["kharedst's memoirs", 'book of the dead'], 'drakans_medallion': ["drakan's medallion"],
    'morytania_legs': ['morytania legs'], 'ardougne_cloak': ['ardougne cloak'], 'ectophial': ['ectophial'],
    'necklace_of_passage': ['necklace of passage'], 'digsite_pendant': ['digsite pendant'], 'pendant_of_ates': ['pendant of ates'],
    'radas_blessing': ["rada's blessing"], 'fremennik_sea_boots': ['fremennik sea boots'], 'desert_amulet': ['desert amulet'],
    'royal_seed_pod': ['royal seed pod'], 'enchanted_lyre': ['enchanted lyre'], 'diary_cape': ['achievement diary cape'],
    'ring_of_shadows': ['ring of shadows'], 'teleport_crystal': ['teleport crystal'], 'karamja_gloves_3': ['karamja gloves 3'],
    'kandarin_headgear': ['kandarin headgear'], 'western_banner': ['western banner'], 'wilderness_sword': ['wilderness sword'], 'wilderness_crabs_teleport': ['wilderness crabs teleport'],
    'camulet': ['camulet'], 'mythical_cape': ['mythical cape'], 'calcified_moth': ['calcified moth'], 'icy_basalt': ['icy basalt'], 'stony_basalt': ['stony basalt'],
    'spider_cave_teleport': ['spider cave teleport'], 'revenant_cave_teleport': ['revenant cave teleport'],
    'mos_leharmless_teleport': ["mos le'harmless teleport", "mos le'harmless teleport scroll"],
    'mortton_teleport': ["mort'ton teleport"], 'lumberyard_teleport': ['lumberyard teleport'],
    'hallowed_crystal_shard': ['hallowed crystal shard'], 'quest_point_cape': ['quest point cape'], 'chronicle': ['chronicle'],
    'fishing_cape': ['fishing cape'], 'farming_cape': ['farming cape'], 'hunter_cape': ['hunter cape'],
    'crafting_cape': ['crafting cape'], 'strength_cape': ['strength cape'], 'skull_sceptre': ['skull sceptre'],
}

SPELLS = ['Ardougne Teleport', 'Falador Teleport', 'Varrock Teleport', 'Camelot Teleport', 'Lumbridge Teleport',
          'Watchtower Teleport', 'Trollheim Teleport', 'Ape Atoll Teleport', 'Kourend Castle Teleport',
          'Civitas illa Fortis Teleport', 'Paddewwa Teleport', 'Senntisten Teleport', 'Kharyrll Teleport', 'Lassar Teleport',
          'Dareeyak Teleport', 'Carrallanger Teleport', 'Annakarl Teleport', 'Ghorrock Teleport', 'Moonclan Teleport',
          'Ourania Teleport', 'Waterbirth Teleport', 'Barbarian Teleport', 'Khazard Teleport', 'Fishing Guild Teleport',
          'Catherby Teleport', 'Ice Plateau Teleport', 'Arceuus Library Teleport', 'Draynor Manor Teleport',
          'Battlefront Teleport', 'Mind Altar Teleport', 'Salve Graveyard Teleport', "Fenkenstrain's Castle Teleport",
          'West Ardougne Teleport', 'Harmony Island Teleport', 'Cemetery Teleport', 'Barrows Teleport']


PORTAL_TOWNS = ['Rimmington', 'Taverley', 'Pollnivneach', 'Hosidius', 'Aldarin', 'Rellekka', 'Brimhaven', 'Yanille', 'Prifddinas']
