"""
Writes SimulatedTask.java and KonarTestTask.java from slayer_locations.json: the tasks, and Konar's task and area
pairs, the dev-only testing plugin can pretend to have. RuneLite's settings can only show fixed dropdowns, so the lists are generated
rather than built at runtime.

    python3 tools/gen_simulated_tasks.py
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'src/main/resources/com/slayerswaps/slayer_locations.json')
OUT = os.path.join(ROOT, 'src/test/java/com/slayerswaps/SimulatedTask.java')
data = json.load(open(DATA))


def ident(text):
    return re.sub(r'_+', '_', re.sub(r'[^A-Z0-9]', '_', text.upper())).strip('_')


def java_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


tasks = sorted((t['name'] for t in data['tasks']), key=str.lower)
consts = ['\tOFF(null),', '\tNO_TASK(null),'] + ['\t%s(%s)%s' % (ident(t), java_str(t), ';' if i == len(tasks) - 1 else ',')
                                                for i, t in enumerate(tasks)]
lines = ['package com.slayerswaps;', '',
         '/**', ' * Tasks the testing plugin can pretend to have.',
         ' * Generated by tools/gen_simulated_tasks.py from slayer_locations.json; don\'t edit by hand.', ' */',
         'public enum SimulatedTask', '{'] + consts + [
         '', '\t// Task name as in slayer_locations.json, or null', '\tprivate final String task;', '',
         '\tSimulatedTask(String task)', '\t{', '\t\tthis.task = task;', '\t}', '',
         '\tpublic String getTask()', '\t{', '\t\treturn task;', '\t}', '',
         '\t@Override', '\tpublic String toString()', '\t{',
         '\t\tswitch (this)', '\t\t{', '\t\t\tcase OFF:', '\t\t\t\treturn "Off";', '\t\t\tcase NO_TASK:',
         '\t\t\t\treturn "No task";', '\t\t\tdefault:', '\t\t\t\treturn task;', '\t\t}', '\t}', '}']
open(OUT, 'w').write('\n'.join(lines) + '\n')
print('wrote', OUT, len(tasks), 'tasks')

KONAR_OUT = os.path.join(ROOT, 'src/test/java/com/slayerswaps/KonarTestTask.java')
pairs = [(t['name'], area) for t in sorted(data['tasks'], key=lambda t: t['name'].lower()) if t.get('konar')
         for area in t['konar']]
consts = ['\tOFF(null, null)' + (',' if pairs else ';')]
for i, (task, area) in enumerate(pairs):
    consts.append('\t%s(%s, %s)%s' % (ident(task + '_' + area), java_str(task), java_str(area),
                                     ';' if i == len(pairs) - 1 else ','))
lines = ['package com.slayerswaps;', '',
         '/**', ' * Konar\'s tasks and areas the testing plugin can pretend to have.',
         ' * Generated by tools/gen_simulated_tasks.py from slayer_locations.json; don\'t edit by hand.', ' */',
         'public enum KonarTestTask', '{'] + consts + [
         '', '\t// Task name as in slayer_locations.json, and Konar\'s area, or null', '\tprivate final String task;',
         '\tprivate final String area;', '',
         '\tKonarTestTask(String task, String area)', '\t{', '\t\tthis.task = task;', '\t\tthis.area = area;', '\t}', '',
         '\tpublic String getTask()', '\t{', '\t\treturn task;', '\t}', '',
         '\tpublic String getArea()', '\t{', '\t\treturn area;', '\t}', '', '\t@Override', '\tpublic String toString()', '\t{',
         '\t\treturn task == null ? "Off" : task + ": " + area;', '\t}', '}']
open(KONAR_OUT, 'w').write('\n'.join(lines) + '\n')
print('wrote', KONAR_OUT, len(pairs), 'Konar tasks')
